branches:
  only:
    - master
    - work
    - travis

language: cpp
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: false
      compiler: gcc
    - os: linux
      dist: bionic
      sudo: false
      compiler: clang
    - os: osx
      compiler: clang
    - os: osx
      osx_image: xcode11
      compiler: clang
install:
    - g++ --version
script:
 - ./configure -b maintain && cd build/maintain && make -j2 Experimental


