branches:
  only:
    - master
    - work
    - travis

language: cpp
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: false
      compiler: gcc
    - os: linux
      dist: bionic
      sudo: false
      compiler: clang
    - os: osx
      compiler: clang
    - os: osx
      osx_image: xcode11
      compiler: clang
    - os: windows
install:
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install strawberryperl; fi
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install nasm; fi
script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./configure -b maintain && cd build/maintain && make -j2 Experimental; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./configure -b maintain && cd build/maintain && make -j2 Experimental; fi
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then export PATH=$PATH:"c:\Program Files\NASM"; fi
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then prerequisites/run_in_visual_studio_2017_environment.sh amd64 bash ./configure -b maintain -f mnt -g "Visual Studio 15 2017 Win64"; fi
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then cd build/mnt; fi
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then travis_wait 20 ../../prerequisites/run_in_visual_studio_2017_environment.sh amd64 bash cmake --build . --config release --target build-openssl; fi
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then travis_wait 30 ../../prerequisites/run_in_visual_studio_2017_environment.sh amd64 bash cmake --build . --config release --target build-boost; fi
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then travis_wait 30 ../../prerequisites/run_in_visual_studio_2017_environment.sh amd64 bash cmake --build . --config release --target Experimental; fi
    # - if [ "$TRAVIS_OS_NAME" == "windows" ]; then travis_wait 40 prerequisites/run_in_visual_studio_2017_environment.sh amd64 bash ./configure -b maintain -f mnt -g "Visual Studio 15 2017 Win64" && cd build/mnt && cmake --build . --config release --target Experimental; fi
    # - if [ "$TRAVIS_OS_NAME" == "windows" ]; then "`find c\:/Program\ Files\ \(x86\)/ -name vcvarsall.bat 2>/dev/null | grep -v -F "Permission" | grep -F "2017"`" amd64; fi
    # - if [ "$TRAVIS_OS_NAME" == "windows" ]; then prerequisites/run_in_visual_studio_2017_environment.sh amd64 bash; fi
    # - if [ "$TRAVIS_OS_NAME" == "windows" ]; then ./configure -b maintain -f maintain -g "Visual Studio 15 2017 Win64" && cd build/maintain; fi
    # - if [ "$TRAVIS_OS_NAME" == "windows" ]; then export PATH=$PATH:"c:\Program Files\NASM"; fi
    # - if [ "$TRAVIS_OS_NAME" == "windows" ]; then travis_wait 20 cmake --build . --config release --target build-openssl; fi
    # - if [ "$TRAVIS_OS_NAME" == "windows" ]; then echo $PATH; fi
    # - if [ "$TRAVIS_OS_NAME" == "windows" ]; then cat /c/Users/travis/build/vipalade/solidframe/build/maintain/external/openssl/src/build-openssl-stamp/build-openssl-configure-err.log; fi
    # - if [ "$TRAVIS_OS_NAME" == "windows" ]; then cat /c/Users/travis/build/vipalade/solidframe/build/maintain/external/openssl/src/build-openssl-stamp/build-openssl-configure-out.log; fi
    # - if [ "$TRAVIS_OS_NAME" == "windows" ]; then cat /c/Users/travis/build/vipalade/solidframe/build/maintain/external/openssl/src/build-openssl-stamp/build-openssl-build-err.log; fi
    # - if [ "$TRAVIS_OS_NAME" == "windows" ]; then cat /c/Users/travis/build/vipalade/solidframe/build/maintain/external/openssl/src/build-openssl-stamp/build-openssl-build-out.log; fi
    # - if [ "$TRAVIS_OS_NAME" == "windows" ]; then travis_wait 30 cmake --build . --config release --target build-boost; fi
    # - if [ "$TRAVIS_OS_NAME" == "windows" ]; then cmake --build . --config release --target Experimental; fi

