branches:
  only:
    - master
    - work
    - travis

language: cpp
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: false
      compiler: gcc
    - os: linux
      dist: bionic
      sudo: false
      compiler: clang
    - os: osx
      compiler: clang
    - os: osx
      osx_image: xcode11
      compiler: clang
    - os: windows
script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./configure -b maintain && cd build/maintain && make -j2 Experimental; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./configure -b maintain && cd build/maintain && make -j2 Experimental; fi
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then ./configure -b maintain && cd build/maintain && cmake --build . --config release; fi

